### PR TITLE
Fix: SplashScreen and portable RIDs

### PR DESCRIPTION
**Pull request by Poker-sang**
* When there is no SplashScreen.png, the first build of the project will have an msbuild error.

* We can use portable RIDs instead of the old, full RID graph according to [MSDN](https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/rid-graph).

### CODE REVIEW

**Comment by Poker-sang** [comment]
Why we need SplashScreen.png:

<https://github.com/Poker-sang/WinUICommunity/blob/8d93b02c37fa277387975a89fa0aa4b1af36cc33/Samples/Package.appxmanifest#L43C7-L43C7>

**Comment by ghost1372** [comment]
Thank you.
 looks good

One question, does this supported for net 7?
Because we have 
```     <TargetFrameworks>net7.0-windows10.0.17763.0;net7.0-windows10.0.19041.0;net8.0-windows10.0.17763.0;net8.0-windows10.0.19041.0</TargetFrameworks>
```

**Comment by ghost1372** [comment]
> Why we need SplashScreen.png:
> 
> <https://github.com/Poker-sang/WinUICommunity/blob/8d93b02c37fa277387975a89fa0aa4b1af36cc33/Samples/Package.appxmanifest#L43C7-L43C7>

**Comment by Poker-sang** [comment]
Sorry I didn't consider this. Maybe I should have kept the Property
Group with condition. But we can still use the new RIDS in .net8.

**Comment by ghost1372** [comment]
> Why we need SplashScreen.png:
> 
> <https://github.com/Poker-sang/WinUICommunity/blob/8d93b02c37fa277387975a89fa0aa4b1af36cc33/Samples/Package.appxmanifest#L43C7-L43C7>

We dont need?
I think this was generated by winui 3 blank project template.

**Comment by ghost1372** [comment]
> Sorry I didn't consider this. Maybe I should keep the `Property Group` with condition. But we can still use the new RIDs in .NET8.

Yes for net 8 we can use new rids

**Comment by Poker-sang** [comment]
But the first time I ran the project he said it was missing SplashScreen.png and could not build the package. When I added this file the problem was solved. Once the app is on the computer, then removing SplashScreen.png will also run it.

**Comment by ghost1372** [comment]
> But the first time I ran the project he said it was missing SplashScreen.png and could not build the package. When I added this file the problem was solved. Once the app is on the computer, then removing SplashScreen.png will also run it.

I will check it today

**Comment by Poker-sang** [comment]
> I think this was generated by winui 3 blank project template.

WinUI 3 blank project template does have SplashScreen.png. but I think you may have accidentally removed it.

**Comment by Poker-sang** [comment]
I edited the file on my phone so I haven't tested it to see if it works. I think it should be fine.

**Comment by ghost1372** [comment]
> I edited the file on my phone so I haven't tested it to see if it works. I think it should be fine.

Thank you i will test it today.

**Comment by ghost1372** [comment]
@Poker-sang i tested and there is a warning:

> warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.

it seems that WindowsAppSDK is not using Portable Rids. so i suggest we keep using `<UseRidGraph>true</UseRidGraph>` and when WindowsAppSDK used portable rids we can move to portable rids.
what do you think?

**Comment by Poker-sang** [comment]
[MSDN](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206) said: If you know your application does not actually need the specified RID — for example, it is not intended to run on the platform specified by the RID — you can suppress the warning using the NoWarn MSBuild property.

We don't run WinUI3 apps on an OS other than win10(win11). So, I thought we can just suppress the warning. It's safe.

**Pull request merged**
